<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'BetterTextLinter' => 'lint/BetterTextLinter.php',
    'ChktexLinter' => 'lint/ChktexLinter.php',
    'LatexTestEngine' => 'unit/LatexTestEngine.php',
  ),
  'function' => array(),
  'xmap' => array(
    'BetterTextLinter' => 'ArcanistLinter',
    'ChktexLinter' => 'ArcanistLinter',
    'LatexTestEngine' => 'ArcanistUnitTestEngine',
  ),
));
